// Source of the generated self-hosted API. The code lives in String.raw blocks, so it must not contain
// backticks or ${} sequences (string concatenation only).

export const SERVER_PACKAGE_JSON = {
  name: 'self-hosted-server',
  version: '1.0.0',
  private: true,
  type: 'module',
  scripts: { start: 'node src/server.mjs' },
  engines: { node: '>=20' },
  dependencies: {
    '@fastify/multipart': '^9.0.1',
    '@fastify/static': '^8.0.3',
    fastify: '^5.2.0',
    pg: '^8.13.1',
  },
};

export const STORAGE_MJS = String.raw`// Local filesystem storage (replaces Base44 cloud storage).
//  - uploadsDir: public files, served at /uploads/<random-name>
//  - privateDir: private files, only reachable through short-lived signed URLs
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { pipeline } from 'node:stream/promises';

export const uploadsDir = path.resolve(process.env.UPLOADS_DIR || '/data/uploads');
export const privateDir = path.resolve(process.env.PRIVATE_DIR || '/data/private');
fs.mkdirSync(uploadsDir, { recursive: true });
fs.mkdirSync(privateDir, { recursive: true });

const SAFE_EXT = /^\.[A-Za-z0-9]{1,10}$/;

async function save(dir, stream, originalName) {
  const ext = path.extname(originalName || '');
  const name = crypto.randomUUID() + (SAFE_EXT.test(ext) ? ext.toLowerCase() : '');
  await pipeline(stream, fs.createWriteStream(path.join(dir, name), { flags: 'wx' }));
  return name;
}

/** Stream an uploaded file to disk under a random name; returns the stored name. */
export const saveUpload = (stream, originalName) => save(uploadsDir, stream, originalName);
export const savePrivate = (stream, originalName) => save(privateDir, stream, originalName);

export const PRIVATE_NAME = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}(\.[a-z0-9]{1,10})?$/;
`;

export const SERVER_MJS = String.raw`// Self-hosted API generated by Base44 Local Converter.
// Entity CRUD, email/password auth, public + private (signed-URL) file storage.
import Fastify from 'fastify';
import fastifyStatic from '@fastify/static';
import multipart from '@fastify/multipart';
import pg from 'pg';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { promisify } from 'node:util';
import { fileURLToPath } from 'node:url';
import { saveUpload, savePrivate, uploadsDir, privateDir, PRIVATE_NAME } from './storage.mjs';

const scrypt = promisify(crypto.scrypt);
const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(here, '..');
const entities = JSON.parse(fs.readFileSync(path.join(root, 'entities.json'), 'utf8'));
const schemaSql = fs.readFileSync(path.join(root, 'schema.sql'), 'utf8');
const authHtml = fs.readFileSync(path.join(here, 'auth.html'), 'utf8');
const publicDir = path.join(root, 'public');

// Return DATE as 'YYYY-MM-DD' (no timezone shift) and BIGINT as a number, matching JSON expectations.
pg.types.setTypeParser(1082, (v) => v);
pg.types.setTypeParser(20, (v) => Number(v));
const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL });
const app = Fastify({ logger: true, bodyLimit: 10 * 1024 * 1024 });
await app.register(multipart, { limits: { fileSize: Number(process.env.MAX_UPLOAD_MB || 50) * 1024 * 1024, files: 1 } });

const qi = (id) => '"' + String(id).replace(/"/g, '""') + '"';
const BUILTIN = { id: 1, created_date: 1, updated_date: 1, created_by: 1 };

// ---------------------------------------------------------------- auth
const AUTH_SECRET = process.env.AUTH_SECRET || crypto.randomBytes(32).toString('hex');
if (!process.env.AUTH_SECRET) app.log.warn('AUTH_SECRET is not set: logins and signed file links reset on every restart');
const TOKEN_TTL_S = 7 * 24 * 3600;
const hmac = (s) => crypto.createHmac('sha256', AUTH_SECRET).update(s).digest('base64url');
const safeEq = (a, b) => { const x = Buffer.from(String(a)); const y = Buffer.from(String(b)); return x.length === y.length && crypto.timingSafeEqual(x, y); };

function signToken(user) {
  const p = Buffer.from(JSON.stringify({ sub: user.id, email: user.email, role: user.role, exp: Math.floor(Date.now() / 1000) + TOKEN_TTL_S })).toString('base64url');
  return p + '.' + hmac(p);
}
function verifyToken(token) {
  if (typeof token !== 'string') return null;
  const [p, s] = token.split('.');
  if (!p || !s || !safeEq(s, hmac(p))) return null;
  try {
    const o = JSON.parse(Buffer.from(p, 'base64url').toString());
    return o.exp > Date.now() / 1000 ? o : null;
  } catch { return null; }
}
async function hashPassword(pw) {
  const salt = crypto.randomBytes(16);
  return salt.toString('hex') + ':' + (await scrypt(pw, salt, 64)).toString('hex');
}
async function checkPassword(pw, stored) {
  const [salt, hash] = String(stored).split(':');
  if (!salt || !hash) return false;
  return safeEq((await scrypt(pw, Buffer.from(salt, 'hex'), 64)).toString('hex'), hash);
}
const publicUser = (u) => ({ id: u.id, email: u.email, full_name: u.full_name, role: u.role });

// naive in-memory brute-force guard: 10 failed logins / 15 min / IP
const failures = new Map();
function tooManyFailures(ip) {
  const now = Date.now();
  const list = (failures.get(ip) || []).filter((t) => now - t < 15 * 60 * 1000);
  failures.set(ip, list);
  return list.length >= 10;
}

app.decorateRequest('user', null);
app.addHook('preHandler', async (req, reply) => {
  const url = req.url.split('?')[0];
  const protectedPath = url.startsWith('/api/entities') || (url.startsWith('/api/files') && !url.startsWith('/api/files/private/'));
  if (!protectedPath) return;
  const h = req.headers.authorization || '';
  const user = h.startsWith('Bearer ') ? verifyToken(h.slice(7)) : null;
  if (!user) return reply.code(401).send({ error: 'Authentication required' });
  req.user = { id: user.sub, email: user.email, role: user.role };
});

app.post('/api/auth/register', async (req, reply) => {
  const { email, password, full_name } = req.body || {};
  const em = String(email || '').trim().toLowerCase();
  if (!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(em)) return reply.code(400).send({ error: 'Invalid email address' });
  if (typeof password !== 'string' || password.length < 8) return reply.code(400).send({ error: 'Password must be at least 8 characters' });
  const count = Number((await pool.query('SELECT count(*) FROM app_users')).rows[0].count);
  if (count > 0 && process.env.ALLOW_REGISTRATION !== 'true') {
    return reply.code(403).send({ error: 'Registration is disabled. Ask an administrator to create your account.' });
  }
  try {
    const role = count === 0 ? 'admin' : 'user';
    const { rows } = await pool.query(
      'INSERT INTO app_users (email, password_hash, full_name, role) VALUES ($1,$2,$3,$4) RETURNING *',
      [em, await hashPassword(password), full_name || null, role],
    );
    return reply.code(201).send({ access_token: signToken(rows[0]), user: publicUser(rows[0]) });
  } catch (e) {
    if (e.code === '23505') return reply.code(409).send({ error: 'An account with this email already exists' });
    throw e;
  }
});

app.post('/api/auth/login', async (req, reply) => {
  if (tooManyFailures(req.ip)) return reply.code(429).send({ error: 'Too many failed attempts. Try again later.' });
  const { email, password } = req.body || {};
  const { rows } = await pool.query('SELECT * FROM app_users WHERE email = $1', [String(email || '').trim().toLowerCase()]);
  const ok = rows[0] && typeof password === 'string' && (await checkPassword(password, rows[0].password_hash));
  if (!ok) {
    failures.get(req.ip).push(Date.now());
    return reply.code(401).send({ error: 'Invalid email or password' });
  }
  return { access_token: signToken(rows[0]), user: publicUser(rows[0]) };
});

app.get('/api/auth/me', async (req, reply) => {
  const h = req.headers.authorization || '';
  const t = h.startsWith('Bearer ') ? verifyToken(h.slice(7)) : null;
  if (!t) return reply.code(401).send({ error: 'Authentication required' });
  const { rows } = await pool.query('SELECT * FROM app_users WHERE id = $1', [t.sub]);
  return rows[0] ? publicUser(rows[0]) : reply.code(401).send({ error: 'Authentication required' });
});
app.post('/api/auth/logout', async (_req, reply) => reply.code(204).send());
// The exported AuthContext treats a 403 with extra_data.reason 'auth_required' as "send the user to login".
app.get('/api/app/public-settings', async (req, reply) => {
  const h = req.headers.authorization || '';
  if (!(h.startsWith('Bearer ') && verifyToken(h.slice(7)))) {
    return reply.code(403).send({ error: 'Authentication required', extra_data: { reason: 'auth_required' } });
  }
  return { id: 'self-hosted', public_settings: {} };
});

// Hosted login / registration page (the exported app has no /login route of its own).
app.get('/login', async (_req, reply) => reply.type('text/html; charset=utf-8').send(authHtml));
app.get('/register', async (_req, reply) => reply.type('text/html; charset=utf-8').send(authHtml));

// ---------------------------------------------------------------- entities
function entityOr404(name, reply) {
  if (!Object.prototype.hasOwnProperty.call(entities, name)) {
    reply.code(404).send({ error: 'Unknown entity: ' + name });
    return null;
  }
  return entities[name];
}

function pickFields(meta, body, reply) {
  if (!body || typeof body !== 'object' || Array.isArray(body)) {
    reply.code(400).send({ error: 'Body must be a JSON object' });
    return null;
  }
  const out = {};
  const unknown = [];
  for (const [k, v] of Object.entries(body)) {
    if (k in BUILTIN) continue;
    const col = Object.prototype.hasOwnProperty.call(meta.columns, k) ? meta.columns[k] : null;
    if (!col) unknown.push(k);
    else out[k] = col.json && v !== null && v !== undefined ? JSON.stringify(v) : v;
  }
  if (unknown.length) {
    reply.code(400).send({ error: 'Unknown field(s): ' + unknown.join(', ') });
    return null;
  }
  return out;
}

function buildWhere(meta, filterJson, reply, params) {
  if (!filterJson) return '';
  let f;
  try { f = JSON.parse(filterJson); } catch { reply.code(400).send({ error: 'q must be JSON' }); return null; }
  if (!f || typeof f !== 'object' || Array.isArray(f)) { reply.code(400).send({ error: 'q must be an object' }); return null; }
  const parts = [];
  for (const [k, v] of Object.entries(f)) {
    if (!(k in BUILTIN) && !Object.prototype.hasOwnProperty.call(meta.columns, k)) { reply.code(400).send({ error: 'Unknown field: ' + k }); return null; }
    if (v === null) parts.push(qi(k) + ' IS NULL');
    else if (typeof v === 'object') { reply.code(400).send({ error: 'Only equality filters are supported (field: ' + k + ')' }); return null; }
    else { params.push(v); parts.push(qi(k) + ' = $' + params.length); }
  }
  return parts.length ? ' WHERE ' + parts.join(' AND ') : '';
}

app.get('/api/health', async () => ({ ok: true }));

app.get('/api/entities/:entity', async (req, reply) => {
  const meta = entityOr404(req.params.entity, reply); if (!meta) return;
  const { sort = '-created_date', limit = '1000', skip = '0', q } = req.query;
  const desc = String(sort).startsWith('-');
  const sortCol = String(sort).replace(/^[-+]/, '');
  if (!(sortCol in BUILTIN) && !Object.prototype.hasOwnProperty.call(meta.columns, sortCol)) return reply.code(400).send({ error: 'Unknown sort field' });
  const params = [];
  const where = buildWhere(meta, q, reply, params); if (where === null) return;
  const lim = Math.min(Math.max(parseInt(limit, 10) || 1000, 1), 10000);
  const off = Math.max(parseInt(skip, 10) || 0, 0);
  const sql = 'SELECT * FROM ' + qi(meta.table) + where + ' ORDER BY ' + qi(sortCol) + (desc ? ' DESC' : ' ASC') + ' LIMIT ' + lim + ' OFFSET ' + off;
  return (await pool.query(sql, params)).rows;
});

app.get('/api/entities/:entity/:id', async (req, reply) => {
  const meta = entityOr404(req.params.entity, reply); if (!meta) return;
  const { rows } = await pool.query('SELECT * FROM ' + qi(meta.table) + ' WHERE id::text = $1', [req.params.id]);
  return rows[0] || reply.code(404).send({ error: 'Not found' });
});

async function insertOne(db, meta, fields, email) {
  const cols = Object.keys(fields).concat(['created_by']);
  const vals = Object.values(fields).concat([email]);
  const sql = 'INSERT INTO ' + qi(meta.table) + ' (' + cols.map(qi).join(',') + ') VALUES (' + vals.map((_, i) => '$' + (i + 1)).join(',') + ') RETURNING *';
  return (await db.query(sql, vals)).rows[0];
}

app.post('/api/entities/:entity', async (req, reply) => {
  const meta = entityOr404(req.params.entity, reply); if (!meta) return;
  const fields = pickFields(meta, req.body, reply); if (!fields) return;
  try { return reply.code(201).send(await insertOne(pool, meta, fields, req.user.email)); }
  catch (e) { req.log.warn(e); return reply.code(400).send({ error: e.message }); }
});

app.post('/api/entities/:entity/bulk', async (req, reply) => {
  const meta = entityOr404(req.params.entity, reply); if (!meta) return;
  if (!Array.isArray(req.body)) return reply.code(400).send({ error: 'Body must be an array' });
  const client = await pool.connect();
  try {
    await client.query('BEGIN');
    const out = [];
    for (const item of req.body) {
      const fields = pickFields(meta, item, reply);
      if (!fields) { await client.query('ROLLBACK'); return; }
      out.push(await insertOne(client, meta, fields, req.user.email));
    }
    await client.query('COMMIT');
    return reply.code(201).send(out);
  } catch (e) { await client.query('ROLLBACK'); req.log.warn(e); return reply.code(400).send({ error: e.message }); }
  finally { client.release(); }
});

async function updateOne(req, reply) {
  const meta = entityOr404(req.params.entity, reply); if (!meta) return;
  const fields = pickFields(meta, req.body, reply); if (!fields) return;
  const keys = Object.keys(fields);
  const sets = keys.map((k, i) => qi(k) + ' = $' + (i + 1)).concat(['updated_date = now()']);
  const params = Object.values(fields).concat([req.params.id]);
  try {
    const { rows } = await pool.query('UPDATE ' + qi(meta.table) + ' SET ' + sets.join(', ') + ' WHERE id::text = $' + params.length + ' RETURNING *', params);
    return rows[0] || reply.code(404).send({ error: 'Not found' });
  } catch (e) { req.log.warn(e); return reply.code(400).send({ error: e.message }); }
}
app.put('/api/entities/:entity/:id', updateOne);
app.patch('/api/entities/:entity/:id', updateOne);

app.delete('/api/entities/:entity/:id', async (req, reply) => {
  const meta = entityOr404(req.params.entity, reply); if (!meta) return;
  const r = await pool.query('DELETE FROM ' + qi(meta.table) + ' WHERE id::text = $1', [req.params.id]);
  return r.rowCount ? reply.code(204).send() : reply.code(404).send({ error: 'Not found' });
});

// ---------------------------------------------------------------- files
app.post('/api/files', async (req, reply) => {
  const file = await req.file();
  if (!file) return reply.code(400).send({ error: 'No file' });
  const name = await saveUpload(file.file, file.filename);
  if (file.file.truncated) return reply.code(413).send({ error: 'File too large' });
  return { file_url: '/uploads/' + name };
});

app.post('/api/files/private', async (req, reply) => {
  const file = await req.file();
  if (!file) return reply.code(400).send({ error: 'No file' });
  const name = await savePrivate(file.file, file.filename);
  if (file.file.truncated) return reply.code(413).send({ error: 'File too large' });
  return { file_uri: name };
});

app.post('/api/files/signed-url', async (req, reply) => {
  const { file_uri, expires_in } = req.body || {};
  if (typeof file_uri !== 'string' || !PRIVATE_NAME.test(file_uri) || !fs.existsSync(path.join(privateDir, file_uri))) {
    return reply.code(404).send({ error: 'File not found' });
  }
  const ttl = Math.min(Math.max(Number(expires_in) || 300, 10), 24 * 3600);
  const exp = Math.floor(Date.now() / 1000) + ttl;
  return { signed_url: '/api/files/private/' + file_uri + '?exp=' + exp + '&sig=' + hmac(file_uri + '.' + exp) };
});

const INLINE_TYPES = { '.pdf': 'application/pdf', '.png': 'image/png', '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg', '.gif': 'image/gif', '.webp': 'image/webp', '.txt': 'text/plain; charset=utf-8' };
app.get('/api/files/private/:name', async (req, reply) => {
  const { name } = req.params;
  const { exp, sig } = req.query;
  if (!PRIVATE_NAME.test(name) || !sig || Number(exp) < Date.now() / 1000 || !safeEq(sig, hmac(name + '.' + exp))) {
    return reply.code(403).send({ error: 'Invalid or expired link' });
  }
  const file = path.join(privateDir, name);
  if (!fs.existsSync(file)) return reply.code(404).send({ error: 'File not found' });
  const type = INLINE_TYPES[path.extname(name)];
  return reply
    .header('x-content-type-options', 'nosniff')
    .header('content-type', type || 'application/octet-stream')
    .header('content-disposition', type ? 'inline' : 'attachment')
    .send(fs.createReadStream(file));
});

// Public uploads: never let the browser render uploaded HTML/SVG/JS as part of this origin.
await app.register(fastifyStatic, {
  root: uploadsDir,
  prefix: '/uploads/',
  decorateReply: false,
  setHeaders(res, p) {
    res.setHeader('X-Content-Type-Options', 'nosniff');
    if (/\.(html?|xhtml|svg|js|mjs)$/i.test(p)) res.setHeader('Content-Disposition', 'attachment');
  },
});

if (fs.existsSync(publicDir)) {
  await app.register(fastifyStatic, { root: publicDir, prefix: '/' });
  app.setNotFoundHandler((req, reply) => {
    // SPA fallback for page routes only; a missing asset (e.g. /manifest.json) is a real 404.
    const p = req.url.split('?')[0];
    if (req.method === 'GET' && !p.startsWith('/api/') && !/\.[a-z0-9]+$/i.test(p)) return reply.sendFile('index.html', publicDir);
    return reply.code(404).send({ error: 'Not found' });
  });
}

await pool.query(
  'CREATE TABLE IF NOT EXISTS app_users (' +
    'id uuid PRIMARY KEY DEFAULT gen_random_uuid(), email text UNIQUE NOT NULL, password_hash text NOT NULL, ' +
    "full_name text, role text NOT NULL DEFAULT 'user', created_date timestamptz NOT NULL DEFAULT now())",
);
await pool.query(schemaSql);
await app.listen({ port: Number(process.env.PORT || 3000), host: '0.0.0.0' });
`;

export const AUTH_HTML = String.raw`<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Sign in</title>
<style>
  body { font-family: system-ui, sans-serif; background: #f4f5f7; display: flex; min-height: 100vh; align-items: center; justify-content: center; margin: 0; }
  form { background: #fff; padding: 28px; border-radius: 12px; width: 340px; box-shadow: 0 2px 12px rgba(0,0,0,.08); }
  h1 { font-size: 20px; margin: 0 0 16px; }
  label { display: block; font-size: 13px; margin: 12px 0 4px; color: #444; }
  input { width: 100%; box-sizing: border-box; padding: 9px 10px; border: 1px solid #ccd; border-radius: 6px; font-size: 14px; }
  button { margin-top: 18px; width: 100%; padding: 10px; border: 0; border-radius: 6px; background: #1f2937; color: #fff; font-size: 14px; cursor: pointer; }
  button:disabled { opacity: .6; }
  .err { color: #b91c1c; font-size: 13px; margin-top: 12px; min-height: 16px; }
  .alt { font-size: 13px; margin-top: 14px; text-align: center; }
</style>
</head>
<body>
<form id="f">
  <h1 id="title">Sign in</h1>
  <label>Email</label><input id="email" type="email" autocomplete="username" required>
  <label>Password</label><input id="password" type="password" autocomplete="current-password" minlength="8" required>
  <div id="confirmRow" hidden><label>Confirm password</label><input id="confirm" type="password" autocomplete="new-password"></div>
  <button id="go" type="submit">Sign in</button>
  <div class="err" id="err"></div>
  <div class="alt" id="alt"></div>
</form>
<script>
(function () {
  var isRegister = location.pathname.indexOf('/register') === 0;
  var params = new URLSearchParams(location.search);
  var rt = params.get('returnTo') || '/';
  try { var u = new URL(rt, location.origin); rt = u.origin === location.origin ? u.pathname + u.search + u.hash : '/'; } catch (e) { rt = '/'; }
  var q = '?returnTo=' + encodeURIComponent(rt);
  document.getElementById('title').textContent = isRegister ? 'Create account' : 'Sign in';
  document.getElementById('go').textContent = isRegister ? 'Create account' : 'Sign in';
  document.getElementById('confirmRow').hidden = !isRegister;
  document.getElementById('alt').innerHTML = isRegister ? '<a href="/login' + q + '">Already have an account? Sign in</a>' : '<a href="/register' + q + '">Create an account</a>';
  document.getElementById('f').addEventListener('submit', function (ev) {
    ev.preventDefault();
    var err = document.getElementById('err'); err.textContent = '';
    var pw = document.getElementById('password').value;
    if (isRegister && pw !== document.getElementById('confirm').value) { err.textContent = 'Passwords do not match'; return; }
    var btn = document.getElementById('go'); btn.disabled = true;
    fetch('/api/auth/' + (isRegister ? 'register' : 'login'), {
      method: 'POST', headers: { 'content-type': 'application/json' },
      body: JSON.stringify({ email: document.getElementById('email').value, password: pw })
    }).then(function (r) { return r.json().then(function (b) { return { ok: r.ok, b: b }; }); })
      .then(function (r) {
        if (!r.ok) throw new Error(r.b.error || 'Failed');
        localStorage.setItem('base44_access_token', r.b.access_token);
        location.href = rt;
      })
      .catch(function (e) { err.textContent = e.message; btn.disabled = false; });
  });
})();
</script>
</body>
</html>
`;
