// Source of the generated self-hosted API. NOTE: written without template literals so it can live in a String.raw block.

export const SERVER_PACKAGE_JSON = {
  name: 'self-hosted-server',
  version: '1.0.0',
  private: true,
  type: 'module',
  scripts: { start: 'node src/server.mjs' },
  engines: { node: '>=20' },
  dependencies: {
    '@fastify/multipart': '^9.0.1',
    '@fastify/static': '^8.0.3',
    fastify: '^5.2.0',
    pg: '^8.13.1',
  },
};

export const STORAGE_MJS = String.raw`// Local filesystem storage for uploaded files (replaces Base44 cloud storage).
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { pipeline } from 'node:stream/promises';

export const uploadsDir = path.resolve(process.env.UPLOADS_DIR || '/data/uploads');
fs.mkdirSync(uploadsDir, { recursive: true });

const SAFE_EXT = /^\.[A-Za-z0-9]{1,10}$/;

/** Stream an uploaded file to disk under a random name; returns the public URL path. */
export async function saveUpload(stream, originalName) {
  const ext = path.extname(originalName || '');
  const name = crypto.randomUUID() + (SAFE_EXT.test(ext) ? ext.toLowerCase() : '');
  const target = path.join(uploadsDir, name);
  await pipeline(stream, fs.createWriteStream(target, { flags: 'wx' }));
  return '/uploads/' + name;
}
`;

export const SERVER_MJS = String.raw`// Self-hosted API generated by Base44 Local Converter.
// Generic CRUD over the entities in entities.json, local file uploads, and a single local user.
import Fastify from 'fastify';
import fastifyStatic from '@fastify/static';
import multipart from '@fastify/multipart';
import pg from 'pg';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { saveUpload, uploadsDir } from './storage.mjs';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(here, '..');
const entities = JSON.parse(fs.readFileSync(path.join(root, 'entities.json'), 'utf8'));
const schemaSql = fs.readFileSync(path.join(root, 'schema.sql'), 'utf8');
const publicDir = path.join(root, 'public');

// Return DATE as 'YYYY-MM-DD' (no timezone shift) and BIGINT as a number, matching JSON expectations.
pg.types.setTypeParser(1082, (v) => v);
pg.types.setTypeParser(20, (v) => Number(v));
const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL });
const app = Fastify({ logger: true, bodyLimit: 10 * 1024 * 1024 });
await app.register(multipart, { limits: { fileSize: Number(process.env.MAX_UPLOAD_MB || 50) * 1024 * 1024, files: 1 } });

const qi = (id) => '"' + String(id).replace(/"/g, '""') + '"';
const BUILTIN = { id: 1, created_date: 1, updated_date: 1, created_by: 1 };
const localUser = {
  id: 'local-user',
  email: process.env.LOCAL_USER_EMAIL || 'admin@localhost',
  full_name: process.env.LOCAL_USER_NAME || 'Local Admin',
  role: 'admin',
};

function entityOr404(name, reply) {
  if (!Object.prototype.hasOwnProperty.call(entities, name)) {
    reply.code(404).send({ error: 'Unknown entity: ' + name });
    return null;
  }
  return entities[name];
}

function pickFields(meta, body, reply) {
  if (!body || typeof body !== 'object' || Array.isArray(body)) {
    reply.code(400).send({ error: 'Body must be a JSON object' });
    return null;
  }
  const out = {};
  const unknown = [];
  for (const [k, v] of Object.entries(body)) {
    if (k in BUILTIN) continue;
    const col = Object.prototype.hasOwnProperty.call(meta.columns, k) ? meta.columns[k] : null;
    if (!col) unknown.push(k);
    else out[k] = col.json && v !== null && v !== undefined ? JSON.stringify(v) : v;
  }
  if (unknown.length) {
    reply.code(400).send({ error: 'Unknown field(s): ' + unknown.join(', ') });
    return null;
  }
  return out;
}

function buildWhere(meta, filterJson, reply, params) {
  if (!filterJson) return '';
  let f;
  try { f = JSON.parse(filterJson); } catch { reply.code(400).send({ error: 'q must be JSON' }); return null; }
  if (!f || typeof f !== 'object' || Array.isArray(f)) { reply.code(400).send({ error: 'q must be an object' }); return null; }
  const parts = [];
  for (const [k, v] of Object.entries(f)) {
    if (!(k in BUILTIN) && !Object.prototype.hasOwnProperty.call(meta.columns, k)) { reply.code(400).send({ error: 'Unknown field: ' + k }); return null; }
    if (v === null) parts.push(qi(k) + ' IS NULL');
    else if (typeof v === 'object') { reply.code(400).send({ error: 'Only equality filters are supported (field: ' + k + ')' }); return null; }
    else { params.push(v); parts.push(qi(k) + ' = $' + params.length); }
  }
  return parts.length ? ' WHERE ' + parts.join(' AND ') : '';
}

app.get('/api/health', async () => ({ ok: true }));

app.get('/api/entities/:entity', async (req, reply) => {
  const meta = entityOr404(req.params.entity, reply); if (!meta) return;
  const { sort = '-created_date', limit = '1000', skip = '0', q } = req.query;
  const desc = String(sort).startsWith('-');
  const sortCol = String(sort).replace(/^[-+]/, '');
  if (!(sortCol in BUILTIN) && !Object.prototype.hasOwnProperty.call(meta.columns, sortCol)) return reply.code(400).send({ error: 'Unknown sort field' });
  const params = [];
  const where = buildWhere(meta, q, reply, params); if (where === null) return;
  const lim = Math.min(Math.max(parseInt(limit, 10) || 1000, 1), 10000);
  const off = Math.max(parseInt(skip, 10) || 0, 0);
  const sql = 'SELECT * FROM ' + qi(meta.table) + where + ' ORDER BY ' + qi(sortCol) + (desc ? ' DESC' : ' ASC') + ' LIMIT ' + lim + ' OFFSET ' + off;
  return (await pool.query(sql, params)).rows;
});

app.get('/api/entities/:entity/:id', async (req, reply) => {
  const meta = entityOr404(req.params.entity, reply); if (!meta) return;
  const { rows } = await pool.query('SELECT * FROM ' + qi(meta.table) + ' WHERE id::text = $1', [req.params.id]);
  return rows[0] || reply.code(404).send({ error: 'Not found' });
});

async function insertOne(meta, fields) {
  const cols = Object.keys(fields).concat(['created_by']);
  const vals = Object.values(fields).concat([localUser.email]);
  const sql = 'INSERT INTO ' + qi(meta.table) + ' (' + cols.map(qi).join(',') + ') VALUES (' + vals.map((_, i) => '$' + (i + 1)).join(',') + ') RETURNING *';
  return (await pool.query(sql, vals)).rows[0];
}

app.post('/api/entities/:entity', async (req, reply) => {
  const meta = entityOr404(req.params.entity, reply); if (!meta) return;
  const fields = pickFields(meta, req.body, reply); if (!fields) return;
  try { return reply.code(201).send(await insertOne(meta, fields)); }
  catch (e) { req.log.warn(e); return reply.code(400).send({ error: e.message }); }
});

app.post('/api/entities/:entity/bulk', async (req, reply) => {
  const meta = entityOr404(req.params.entity, reply); if (!meta) return;
  if (!Array.isArray(req.body)) return reply.code(400).send({ error: 'Body must be an array' });
  const client = await pool.connect();
  try {
    await client.query('BEGIN');
    const out = [];
    for (const item of req.body) {
      const fields = pickFields(meta, item, reply); if (!fields) { await client.query('ROLLBACK'); return; }
      const cols = Object.keys(fields).concat(['created_by']);
      const vals = Object.values(fields).concat([localUser.email]);
      const sql = 'INSERT INTO ' + qi(meta.table) + ' (' + cols.map(qi).join(',') + ') VALUES (' + vals.map((_, i) => '$' + (i + 1)).join(',') + ') RETURNING *';
      out.push((await client.query(sql, vals)).rows[0]);
    }
    await client.query('COMMIT');
    return reply.code(201).send(out);
  } catch (e) { await client.query('ROLLBACK'); req.log.warn(e); return reply.code(400).send({ error: e.message }); }
  finally { client.release(); }
});

async function updateOne(req, reply) {
  const meta = entityOr404(req.params.entity, reply); if (!meta) return;
  const fields = pickFields(meta, req.body, reply); if (!fields) return;
  const keys = Object.keys(fields);
  const sets = keys.map((k, i) => qi(k) + ' = $' + (i + 1)).concat(['updated_date = now()']);
  const params = Object.values(fields).concat([req.params.id]);
  try {
    const { rows } = await pool.query('UPDATE ' + qi(meta.table) + ' SET ' + sets.join(', ') + ' WHERE id::text = $' + params.length + ' RETURNING *', params);
    return rows[0] || reply.code(404).send({ error: 'Not found' });
  } catch (e) { req.log.warn(e); return reply.code(400).send({ error: e.message }); }
}
app.put('/api/entities/:entity/:id', updateOne);
app.patch('/api/entities/:entity/:id', updateOne);

app.delete('/api/entities/:entity/:id', async (req, reply) => {
  const meta = entityOr404(req.params.entity, reply); if (!meta) return;
  const r = await pool.query('DELETE FROM ' + qi(meta.table) + ' WHERE id::text = $1', [req.params.id]);
  return r.rowCount ? reply.code(204).send() : reply.code(404).send({ error: 'Not found' });
});

// --- auth: single local user. Replace with real authentication before exposing publicly. ---
app.get('/api/auth/me', async () => localUser);
app.post('/api/auth/logout', async (_req, reply) => reply.code(204).send());

// --- files ---
app.post('/api/files', async (req, reply) => {
  const file = await req.file();
  if (!file) return reply.code(400).send({ error: 'No file' });
  const url = await saveUpload(file.file, file.filename);
  if (file.file.truncated) return reply.code(413).send({ error: 'File too large' });
  return { file_url: url };
});
await app.register(fastifyStatic, { root: uploadsDir, prefix: '/uploads/', decorateReply: false });

if (fs.existsSync(publicDir)) {
  await app.register(fastifyStatic, { root: publicDir, prefix: '/' });
  app.setNotFoundHandler((req, reply) => {
    if (req.method === 'GET' && !req.url.startsWith('/api/')) return reply.sendFile('index.html', publicDir);
    return reply.code(404).send({ error: 'Not found' });
  });
}

await pool.query(schemaSql);
await app.listen({ port: Number(process.env.PORT || 3000), host: '0.0.0.0' });
`;
