// Browser-side replacement for the parts of @base44/sdk that map onto the generated REST API.
// Everything else throws a clear "not implemented" error instead of failing silently.
// Written without backticks / ${} so it can live in a String.raw block.

export const SHIM_JS = String.raw`// Generated by Base44 Local Converter. Replaces '@base44/sdk' in the self-hosted build.
const API = (import.meta.env && import.meta.env.VITE_API_BASE) || '/api';
const TOKEN_KEYS = ['base44_access_token', 'token'];

function notImplemented(name) {
  return () => {
    throw new Error('[base44-local] ' + name + ' is not implemented in the self-hosted build. See MIGRATION_REPORT.md.');
  };
}

export function getAccessToken() {
  try {
    for (const k of TOKEN_KEYS) {
      const v = window.localStorage.getItem(k);
      if (v) return v;
    }
  } catch {}
  return null;
}

function setToken(token) {
  try {
    window.localStorage.setItem('base44_access_token', token);
  } catch {}
}

function clearToken() {
  try {
    for (const k of TOKEN_KEYS) window.localStorage.removeItem(k);
  } catch {}
}

function goToLogin(returnTo) {
  window.location.href = '/login' + (returnTo ? '?returnTo=' + encodeURIComponent(returnTo) : '');
}

async function request(method, url, body, isForm) {
  const headers = {};
  const token = getAccessToken();
  if (token) headers.Authorization = 'Bearer ' + token;
  if (body !== undefined && !isForm) headers['content-type'] = 'application/json';
  const res = await fetch(API + url, {
    method,
    headers,
    body: body === undefined ? undefined : isForm ? body : JSON.stringify(body),
  });
  if (!res.ok) {
    let data = null;
    try { data = await res.json(); } catch {}
    const err = new Error((data && data.error) || res.statusText);
    err.status = res.status;
    err.data = data; // same shape the Base44 SDK exposes (e.g. data.extra_data.reason)
    throw err;
  }
  return res.status === 204 ? null : res.json();
}

function qs(params) {
  const u = new URLSearchParams();
  for (const [k, v] of Object.entries(params)) if (v !== undefined && v !== null) u.set(k, String(v));
  const s = u.toString();
  return s ? '?' + s : '';
}

function entityApi(name) {
  const base = '/entities/' + encodeURIComponent(name);
  return {
    list: (sort, limit, skip) => request('GET', base + qs({ sort, limit, skip })),
    filter: (query, sort, limit, skip) => request('GET', base + qs({ q: JSON.stringify(query || {}), sort, limit, skip })),
    get: (id) => request('GET', base + '/' + encodeURIComponent(id)),
    create: (data) => request('POST', base, data),
    bulkCreate: (items) => request('POST', base + '/bulk', items),
    update: (id, data) => request('PATCH', base + '/' + encodeURIComponent(id), data),
    delete: (id) => request('DELETE', base + '/' + encodeURIComponent(id)),
  };
}

function strictProxy(label, impl) {
  return new Proxy(impl, {
    get(target, prop) {
      if (typeof prop !== 'string' || prop === 'then') return undefined;
      return prop in target ? target[prop] : notImplemented(label + '.' + prop);
    },
  });
}

function upload(path) {
  return async ({ file }) => {
    const form = new FormData();
    form.append('file', file);
    return request('POST', path, form, true);
  };
}

async function authenticate(path, body) {
  const result = await request('POST', path, body);
  if (result && result.access_token) setToken(result.access_token);
  return result;
}

export function createClient() {
  const entities = new Proxy({}, { get: (_t, name) => (typeof name === 'string' && name !== 'then' ? entityApi(name) : undefined) });
  return {
    entities,
    app: strictProxy('app', { getPublicSettings: () => request('GET', '/app/public-settings') }),
    auth: strictProxy('auth', {
      me: () => request('GET', '/auth/me'),
      isAuthenticated: async () => {
        if (!getAccessToken()) return false;
        try { await request('GET', '/auth/me'); return true; } catch { return false; }
      },
      loginViaEmailPassword: (email, password) => authenticate('/auth/login', { email, password }),
      register: ({ email, password, full_name }) => authenticate('/auth/register', { email, password, full_name }),
      setToken,
      logout: (redirectUrl) => {
        clearToken();
        if (redirectUrl) goToLogin(redirectUrl);
      },
      redirectToLogin: (returnTo) => goToLogin(returnTo),
      // Not available self-hosted (they need an email service / OAuth provider):
      //   verifyOtp, resendOtp, resetPasswordRequest, resetPassword, loginWithProvider
    }),
    integrations: strictProxy('integrations', {
      Core: strictProxy('integrations.Core', {
        UploadFile: upload('/files'),
        UploadPrivateFile: upload('/files/private'),
        CreateFileSignedUrl: ({ file_uri, expires_in }) => request('POST', '/files/signed-url', { file_uri, expires_in }),
      }),
    }),
    functions: strictProxy('functions', {}),
    agents: strictProxy('agents', {}),
    analytics: strictProxy('analytics', { track: () => {} }),
    asServiceRole: strictProxy('asServiceRole', {}),
  };
}
`;

export const SHIM_DTS = `export function createClient(config?: unknown): any;
export function getAccessToken(): string | null;
`;
