// Browser-side replacement for the parts of @base44/sdk that map onto the generated REST API.
// Everything else throws a clear "not implemented" error instead of failing silently.

export const SHIM_JS = String.raw`// Generated by Base44 Local Converter. Replaces '@base44/sdk' in the self-hosted build.
const API = (import.meta.env && import.meta.env.VITE_API_BASE) || '/api';

function notImplemented(name) {
  return () => {
    throw new Error('[base44-local] ' + name + ' is not implemented in the self-hosted build. See MIGRATION_REPORT.md.');
  };
}

async function request(method, url, body) {
  const res = await fetch(API + url, {
    method,
    headers: body !== undefined ? { 'content-type': 'application/json' } : undefined,
    body: body !== undefined ? JSON.stringify(body) : undefined,
    credentials: 'same-origin',
  });
  if (!res.ok) {
    let msg = res.statusText;
    try { msg = (await res.json()).error || msg; } catch {}
    const err = new Error(msg);
    err.status = res.status;
    throw err;
  }
  return res.status === 204 ? null : res.json();
}

function qs(params) {
  const u = new URLSearchParams();
  for (const [k, v] of Object.entries(params)) if (v !== undefined && v !== null) u.set(k, String(v));
  const s = u.toString();
  return s ? '?' + s : '';
}

function entityApi(name) {
  const base = '/entities/' + encodeURIComponent(name);
  return {
    list: (sort, limit, skip) => request('GET', base + qs({ sort, limit, skip })),
    filter: (query, sort, limit, skip) => request('GET', base + qs({ q: JSON.stringify(query || {}), sort, limit, skip })),
    get: (id) => request('GET', base + '/' + encodeURIComponent(id)),
    create: (data) => request('POST', base, data),
    bulkCreate: (items) => request('POST', base + '/bulk', items),
    update: (id, data) => request('PATCH', base + '/' + encodeURIComponent(id), data),
    delete: (id) => request('DELETE', base + '/' + encodeURIComponent(id)),
  };
}

function strictProxy(label, impl) {
  return new Proxy(impl, {
    get(target, prop) {
      if (typeof prop !== 'string' || prop === 'then') return undefined;
      return prop in target ? target[prop] : notImplemented(label + '.' + prop);
    },
  });
}

async function uploadFile({ file }) {
  const form = new FormData();
  form.append('file', file);
  const res = await fetch(API + '/files', { method: 'POST', body: form });
  if (!res.ok) throw new Error('Upload failed: ' + res.status);
  return res.json();
}

export function createClient() {
  const entities = new Proxy({}, { get: (_t, name) => (typeof name === 'string' && name !== 'then' ? entityApi(name) : undefined) });
  return {
    entities,
    auth: strictProxy('auth', {
      me: () => request('GET', '/auth/me'),
      isAuthenticated: async () => true,
      logout: async () => { await request('POST', '/auth/logout'); },
      redirectToLogin: () => {},
    }),
    integrations: strictProxy('integrations', { Core: strictProxy('integrations.Core', { UploadFile: uploadFile }) }),
    functions: strictProxy('functions', {}),
    agents: strictProxy('agents', {}),
    analytics: strictProxy('analytics', { track: () => {} }),
    asServiceRole: strictProxy('asServiceRole', {}),
  };
}
`;

export const SHIM_DTS = `export function createClient(config?: unknown): any;
`;
