import fs from 'node:fs/promises';
import path from 'node:path';
import type { MigrationContext } from './context';
import { AUTH_HTML, SERVER_MJS, SERVER_PACKAGE_JSON } from './templates/server';

const BUILD_FRAMEWORKS = new Set(['vite-react', 'vite-vue', 'vite-svelte', 'vite-vanilla', 'cra-react']);

function dockerfile(ctx: MigrationContext): string {
  const fw = ctx.analysis.framework;
  const buildDir = ctx.analysis.frontendBuildDir ?? 'dist';
  const lines: string[] = [];
  let webCopy: string;
  if (BUILD_FRAMEWORKS.has(fw)) {
    lines.push(
      '# --- build the frontend ---',
      'FROM node:22-alpine AS web',
      'WORKDIR /web',
      'COPY app/package*.json ./',
      'RUN npm install --no-audit --no-fund',
      'COPY app/ ./',
      'RUN npm run build',
      '',
    );
    webCopy = `COPY --from=web /web/${buildDir} ./public`;
  } else if (fw === 'static-html') {
    webCopy = 'COPY app/ ./public';
  } else {
    webCopy = '# Frontend framework not supported for automatic packaging: build it yourself and place the output in ./public';
  }
  lines.push(
    '# --- API + static frontend ---',
    'FROM node:22-alpine',
    'WORKDIR /srv',
    'ENV NODE_ENV=production',
    'COPY server/package*.json ./',
    'RUN npm install --omit=dev --no-audit --no-fund',
    'COPY server/ ./',
    webCopy,
    'ENV PORT=3000 UPLOADS_DIR=/data/uploads PRIVATE_DIR=/data/private',
    'EXPOSE 3000',
    'CMD ["node", "src/server.mjs"]',
    '',
  );
  return lines.join('\n');
}

const COMPOSE = `services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: \${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: \${POSTGRES_PASSWORD:?set POSTGRES_PASSWORD in .env}
      POSTGRES_DB: \${POSTGRES_DB:-app}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \${POSTGRES_USER:-app} -d \${POSTGRES_DB:-app}"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://\${POSTGRES_USER:-app}:\${POSTGRES_PASSWORD}@db:5432/\${POSTGRES_DB:-app}
      UPLOADS_DIR: /data/uploads
      PRIVATE_DIR: /data/private
      MAX_UPLOAD_MB: \${MAX_UPLOAD_MB:-50}
      AUTH_SECRET: \${AUTH_SECRET:?set AUTH_SECRET in .env (long random string)}
      ALLOW_REGISTRATION: \${ALLOW_REGISTRATION:-false}
    ports:
      - "\${APP_PORT:-3000}:3000"
    volumes:
      - files:/data

volumes:
  pgdata:
  files:
`;

const ENV_EXAMPLE = `# Copy to .env and edit
POSTGRES_USER=app
POSTGRES_PASSWORD=change-me
POSTGRES_DB=app
APP_PORT=3000
MAX_UPLOAD_MB=50
# Signs login tokens and private-file links. Generate with: openssl rand -hex 32
AUTH_SECRET=change-me-to-a-long-random-string
# The first account registered at /register becomes admin. Keep false to block further sign-ups.
ALLOW_REGISTRATION=false
`;

function readme(ctx: MigrationContext): string {
  return `# Self-hosted project

Generated by Base44 Local Converter. **Read MIGRATION_REPORT.md first** - it lists everything that needs manual work.

## Layout
- \`original/\`  untouched Base44 source
- \`app/\`       converted frontend (Base44 SDK replaced by \`${ctx.shimPath ?? 'n/a'}\`)
- \`server/\`    generated API (Fastify + PostgreSQL + local uploads)
- \`Dockerfile\`, \`docker-compose.yml\`, \`.env.example\`

## Run
\`\`\`
cp .env.example .env     # set POSTGRES_PASSWORD
docker compose up -d --build
\`\`\`
Open http://localhost:3000. Files live in the \`files\` volume (\`/data/uploads\` public, \`/data/private\` private).

## First login
1. Set a long random \`AUTH_SECRET\` in \`.env\`.
2. Open \`/register\` and create the first account. **The first account becomes the admin.**
3. Further sign-ups are blocked unless \`ALLOW_REGISTRATION=true\`.

## Important
- Auth is email + password only. Email verification (OTP), password-reset emails and Google/OAuth login are **not** available; see MIGRATION_REPORT.md.
- Roles from the token are not re-checked per request and no entity-level access rules are enforced: every signed-in user can read and write every entity.
- Existing Base44 data is not included in a code export and must be imported separately.
`;
}

export async function generateConfig(ctx: MigrationContext): Promise<void> {
  const w = async (rel: string, content: string) => {
    const abs = path.join(ctx.projectDir, rel);
    await fs.mkdir(path.dirname(abs), { recursive: true });
    await fs.writeFile(abs, content);
    ctx.changes.push({ file: rel, kind: 'add-file', detail: 'generated' });
  };
  await w('server/package.json', JSON.stringify(SERVER_PACKAGE_JSON, null, 2) + '\n');
  await w('server/src/server.mjs', SERVER_MJS);
  await w('server/src/auth.html', AUTH_HTML);
  await w('Dockerfile', dockerfile(ctx));
  await w('docker-compose.yml', COMPOSE);
  await w('.env.example', ENV_EXAMPLE);
  await w('.dockerignore', 'original\n**/node_modules\n.env\n');
  await w('README.md', readme(ctx));
}
