import fs from 'node:fs/promises';
import path from 'node:path';
import { SAFE_IDENT, snakeCase } from '@b44/shared';
import type { EntityTable, MigrationContext } from './context';

const BUILTIN_COLUMNS = ['id', 'created_date', 'updated_date', 'created_by'];

const q = (id: string) => `"${id.replace(/"/g, '""')}"`;
const lit = (s: string) => `'${s.replace(/'/g, "''")}'`;

interface MappedType {
  pgType: string;
  json: boolean;
}

export function mapType(prop: any): MappedType | null {
  const t = prop?.type;
  const fmt = prop?.format;
  switch (t) {
    case 'string':
      if (fmt === 'date-time') return { pgType: 'timestamptz', json: false };
      if (fmt === 'date') return { pgType: 'date', json: false };
      return { pgType: 'text', json: false };
    case 'number':
      return { pgType: 'double precision', json: false };
    case 'integer':
      return { pgType: 'bigint', json: false };
    case 'boolean':
      return { pgType: 'boolean', json: false };
    case 'array':
    case 'object':
      return { pgType: 'jsonb', json: true };
    default:
      return null;
  }
}

function defaultClause(prop: any, m: MappedType): string {
  const d = prop?.default;
  if (d === undefined || d === null) return '';
  if (m.json) return ` DEFAULT ${lit(JSON.stringify(d))}::jsonb`;
  if (typeof d === 'boolean') return ` DEFAULT ${d}`;
  if (typeof d === 'number' && Number.isFinite(d)) return ` DEFAULT ${d}`;
  if (typeof d === 'string' && m.pgType === 'text') return ` DEFAULT ${lit(d)}`;
  return '';
}

/** Generate server/schema.sql and server/entities.json from the entity schemas found in the export. */
export async function generateDatabase(ctx: MigrationContext): Promise<void> {
  const tables: EntityTable[] = [];
  const sql: string[] = [
    '-- Generated by Base44 Local Converter from the exported entity schemas.',
    '-- Idempotent: safe to run on every start.',
    '',
  ];
  const usedTables = new Set<string>();

  for (const ent of ctx.analysis.base44.entities) {
    if (!SAFE_IDENT.test(ent.name)) {
      ctx.addFinding({ severity: 'manual', category: 'database', message: `Entity name "${ent.name}" is not a safe identifier; skipped.`, file: ent.file });
      continue;
    }
    const table = snakeCase(ent.name);
    if (usedTables.has(table)) {
      ctx.addFinding({ severity: 'manual', category: 'database', message: `Entity "${ent.name}" maps to duplicate table "${table}"; skipped.`, file: ent.file });
      continue;
    }
    usedTables.add(table);

    const props = (ent.schema.properties ?? {}) as Record<string, any>;
    const required = new Set<string>(Array.isArray(ent.schema.required) ? (ent.schema.required as string[]) : []);
    const columns: EntityTable['columns'] = {};
    const defs: string[] = [
      `  ${q('id')} uuid PRIMARY KEY DEFAULT gen_random_uuid()`,
      `  ${q('created_date')} timestamptz NOT NULL DEFAULT now()`,
      `  ${q('updated_date')} timestamptz NOT NULL DEFAULT now()`,
      `  ${q('created_by')} text`,
    ];
    const checks: string[] = [];

    for (const [col, prop] of Object.entries(props)) {
      if (!SAFE_IDENT.test(col) || BUILTIN_COLUMNS.includes(col)) {
        ctx.addFinding({
          severity: 'warning',
          category: 'database',
          message: `Field ${ent.name}.${col} skipped (${BUILTIN_COLUMNS.includes(col) ? 'reserved built-in column' : 'unsafe identifier'}).`,
          file: ent.file,
        });
        continue;
      }
      let m = mapType(prop);
      if (!m) {
        m = { pgType: 'jsonb', json: true };
        ctx.addFinding({ severity: 'warning', category: 'database', message: `Field ${ent.name}.${col} has no recognised type; stored as jsonb.`, file: ent.file });
      }
      columns[col] = m;
      const notNull = required.has(col) ? ' NOT NULL' : '';
      defs.push(`  ${q(col)} ${m.pgType}${notNull}${defaultClause(prop, m)}`);
      if (Array.isArray(prop?.enum) && prop.enum.length > 0 && prop.enum.every((v: unknown) => typeof v === 'string') && m.pgType === 'text') {
        checks.push(`  CONSTRAINT ${q(`${table}_${col}_enum`)} CHECK (${q(col)} IS NULL OR ${q(col)} IN (${prop.enum.map(lit).join(', ')}))`);
      }
    }

    sql.push(`CREATE TABLE IF NOT EXISTS ${q(table)} (\n${[...defs, ...checks].join(',\n')}\n);`, '');
    tables.push({ name: ent.name, table, columns });
    ctx.log('info', `Entity ${ent.name} -> table ${table} (${Object.keys(columns).length} fields)`);
  }

  ctx.entityTables = tables;
  await fs.mkdir(ctx.serverDir, { recursive: true });
  await fs.writeFile(path.join(ctx.serverDir, 'schema.sql'), sql.join('\n'));
  const meta = Object.fromEntries(tables.map((t) => [t.name, { table: t.table, columns: t.columns }]));
  await fs.writeFile(path.join(ctx.serverDir, 'entities.json'), JSON.stringify(meta, null, 2));
  ctx.changes.push({ file: 'server/schema.sql', kind: 'add-file', detail: `${tables.length} table(s)` });
  ctx.changes.push({ file: 'server/entities.json', kind: 'add-file', detail: 'entity metadata used by the generated API' });
}
